// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: network/proto/testing.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GenericMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GenericMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenericMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GenericMessageMultiError,
// or nil if none found.
func (m *GenericMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *GenericMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return GenericMessageMultiError(errors)
	}

	return nil
}

// GenericMessageMultiError is an error wrapping multiple validation errors
// returned by GenericMessage.ValidateAll() if the designated constraints
// aren't met.
type GenericMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenericMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenericMessageMultiError) AllErrors() []error { return m }

// GenericMessageValidationError is the validation error returned by
// GenericMessage.Validate if the designated constraints aren't met.
type GenericMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenericMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenericMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenericMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenericMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenericMessageValidationError) ErrorName() string { return "GenericMessageValidationError" }

// Error satisfies the builtin error interface
func (e GenericMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenericMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenericMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenericMessageValidationError{}

// Validate checks the field values on ChattyRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChattyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChattyRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChattyRequestMultiError, or
// nil if none found.
func (m *ChattyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ChattyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Count

	if len(errors) > 0 {
		return ChattyRequestMultiError(errors)
	}

	return nil
}

// ChattyRequestMultiError is an error wrapping multiple validation errors
// returned by ChattyRequest.ValidateAll() if the designated constraints
// aren't met.
type ChattyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChattyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChattyRequestMultiError) AllErrors() []error { return m }

// ChattyRequestValidationError is the validation error returned by
// ChattyRequest.Validate if the designated constraints aren't met.
type ChattyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChattyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChattyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChattyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChattyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChattyRequestValidationError) ErrorName() string { return "ChattyRequestValidationError" }

// Error satisfies the builtin error interface
func (e ChattyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChattyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChattyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChattyRequestValidationError{}
